[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "docs/dist"

  command = "pnpm install --shamefully-hoist && cd packages/vue-final-modal && pnpm build && cd .. && cd .. && cd docs && pnpm generate"