[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "packages/docs/.output/public"

  command = "pnpm install --shamefully-hoist && cd packages/vue-final-modal && pnpm build && cd .. && cd docs && pnpm generate"