name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install pnpm
        run: |
          npm install pnpm@next -g
          pnpm --version
      - name: pnpm install
        run: pnpm recursive install
      - name: pnpm test
        run: pnpm test
