name: GitHub Actions Demo
on: ["push", "pull_request"]
jobs:
  pnpm-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install pnpm
        run: |
          npm install pnpm@next -g
          pnpm --version
      - name: pnpm install
        run: pnpm recursive install
      - name: pnpm test
        run: COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} pnpm coveralls
